[build]
  base = "."
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  # DATABASE_URL must be set in Netlify Dashboard → Site settings → Environment variables
  # OPENAI_API_KEY must be set in Netlify Dashboard → Site settings → Environment variables

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
